language: node_js
node_js: node
services:
  - postgresql
cache:
  directories:
    - node_modules
branches:
  only:
    - master
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
script:
  - yarn start validate.withCoverage
after_success:
  - yarn start reportCoverage
